### ISSUE TITLE
User Class Unnecessary

### ISSUE THREAD

**Issue by ConnorMacDonell** [joehernandez11/Twitter_Project#3]
While the user class that you have created may be quite useful down the road, it doesn't seem to be totally necessary for this project. One suggestion I would make is to focus on making classes that will be needed for the task at hand. I would not bother making a class like this which is not necessary to the assignment, I would suggest that you may be able to spend your time better by only writing code for the specific project you are completing.

**Comment by joehernandez11** [comment]
I understand what you're saying. Thanks for reviewing what I have.
