### ISSUE TITLE
On The Right Track

### ISSUE THREAD

**Issue by dallen4** [joehernandez11/Twitter_Project#5]
You seem to be on the right track and I love the simplicity of your classes. I don't think you need a separate class for URLs and if you want to go down a similar path I would recommend using maybe a struct (or maybe an enum -- I think I saw a classmate of ours do that). I suggest this because you could be able to analyze the attributes and label/define more easily and the compiler would not have to create an entire class for something that could be solved with a simpler data structure.

**Comment by joehernandez11** [comment]
Okay I'll look and see what I can do to simplify this up a little more. Thanks for reviewing what I have!
